<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>x.ovo.jbot</groupId>
        <artifactId>jbot-parent</artifactId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>jbot-plugins</artifactId>
    <packaging>pom</packaging>
    <description>jbot插件</description>
    <modules>
        <module>jbot-plugin-pm</module>
        <module>jbot-plugin-kfc</module>
        <module>jbot-plugin-js_example</module>
        <module>jbot-plugin-memory</module>
        <module>jbot-plugin-news</module>
        <module>jbot-plugin-onset</module>
        <module>jbot-plugin-epic</module>
        <module>jbot-plugin-music</module>
        <module>jbot-plugin-reread</module>
        <module>jbot-plugin-tips</module>
        <module>jbot-plugin-card</module>
        <module>jbot-plugin-ai</module>
        <module>jbot-plugin-push</module>
    </modules>

    <dependencies>
        <dependency>
            <groupId>x.ovo.jbot</groupId>
            <artifactId>jbot-core</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>io.vertx</groupId>
            <artifactId>vertx-core</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.dromara.hutool</groupId>
            <artifactId>hutool-core</artifactId>
            <scope>provided</scope>
        </dependency>
    </dependencies>

    <build>
        <finalName>${project.artifactId}</finalName>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.5.3</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <minimizeJar>true</minimizeJar>
                    <createDependencyReducedPom>false</createDependencyReducedPom>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>